sudo: required
services:
  - docker

before_install:
  - docker build -t amitkertis17/docker-react -f Dockerfile .

script:
  - docker run -e CI=true amitkertis17/docker-react npm run test -- --coverage

